name: maze
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip:
      - gymnasium
      - gymnasium[mujoco]
      - mujoco
      - stable-baselines3>=2.0
      - tensorboard
      - cloudpickle
      - accelerate
      - transformers
      - huggingface-hub
      - tokenizers
      - einops
      - torchmetrics
      - gradio
      - crewai
      - faiss-cpu
      - openai
      - python-dotenv
      - requests
      - fsspec
      - pygame
      - opencv-python
      - tqdm
      - google-api-python-client
      - google-auth-oauthlib
      - google-auth-httplib2
      - statsmodels
